---

- name: Enable Oracle JDK 7 PPA
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Configure debconf for unattended installation
  sudo: yes
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Install Oracle JDK 7
  sudo: yes
  apt: pkg=oracle-java7-installer state=latest update_cache=yes
